# The URL the site will be built for
base_url = "https://turboladen.github.io/curiousconcoctor"

title = "The Curious Concoctor"
description = "Exploring godly concoctions for mortals."
author = "Steve Loveless"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Build rss.xml for the site and for each taxonomy term whose taxonomy sets feed = true.
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
  { name = "drink_types", feed = true },
  { name = "tags" },
  { name = "post_types", feed = true },
]

[markdown]
# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = true

# Whether to set decoding="async" and loading="lazy" for all images
# When turned on, the alt text must be plain text.
# For example, `![xx](...)` is ok but `![*x*x](...)` isn’t ok
lazy_async_image = true

[extra]
menu_links = [
  { url = "$BASE_URL", name = "Home" },
  { url = "$BASE_URL/drink-types", name = "Drink Types" },
  { url = "$BASE_URL/post-types", name = "Post Types" },
  { url = "$BASE_URL/tags", name = "Tags" },
  { url = "$BASE_URL/about", name = "About" },
  { url = "$BASE_URL/rss.xml", name = "RSS" },
]
ogimage = "og-image.png"
